### PR TITLE
various improvements

### PR DESCRIPTION
**Pull request by disaster123**
* remove unneeded Access-Control-Allow-Origin headers - this is never cross domain
* correctly use vars expected_header_status and authentication_page_status_output
* simplify and faster exit in case of ajax request
* default authentication_page_status_output status to 503 otherwise google and other crawlers index this page

### CODE REVIEW

**Comment by C0nw0nk** [comment]
Nothing wrong with your improvements other than a slight bug I encountered when I was originally building this.

So to explain it.

You added in this on line 515.

```
ngx.header["Set-Cookie"] 
```

Now the reason you see in the script I only define this header once and I define it at the very end of the script is because Nginx Lua was not sending the set cookie header when you define set cookie multiple times in one script. It is a odd bug but to be safe keep it defined once at the end of the script and use the `local variable` of `set_cookies` to add the cookies you want to it like I do.

You are welcome to test by defining multiple

```
ngx.header["Set-Cookie"]  = "hello_1"
ngx.header["Set-Cookie"]  = "hello_2"
```

And checking your browsers headers to see what cookie headers you get In firefox and chrome i stumbled across this.

I don't see the issue with sticking with the one defined at the end to be honnest we don't need anymore.

I will have a junk code clean up soon.

Have a test and play around and see if you can replicate what i explain about defining it more than once.

**Comment by disaster123** [comment]
Mhm i don't get it - also it's tested and working fine under Chrome, Chromium, Safari and Firefox.

Your example simply overwrites the original definition and should only set hello_2 which makes absolutely sense but in my code you have:
```
ngx.header["Set-Cookie"] = set_cookies
...
ngx.exit(ngx.HTTP_OK)
```

So there is no 2nd Set-Cookie call in the fast exit path of grant_access and XMLHttpRequest.

**Comment by C0nw0nk** [comment]
As @agentzh who built Lua for Nginx and worked for Cloudflare said here.

https://github.com/openresty/lua-nginx-module/issues/19#issuecomment-19999749

> You can collect all the cookies in your Lua loop in a Lua table, and assign it after the loop in a single run.

I don't know if it got fixed since then in newer versions of Lua but for compatibility i will leave it defined once at the end of the script it does not need to be specified multiple times anyway. Keeps code cleaner, smaller and more optimized.

**Comment by C0nw0nk** [comment]
If you google you will find posts like this. https://stackoverflow.com/questions/44016867/how-come-i-cannot-set-multiple-cookies

Allot of people encountered it not just me.

**Comment by disaster123** [comment]
Sorry but this is simply not the case here. All your provided examples are correct and i confirm them but we don't have this case here.

They're talking about:
```
ngx.header["Set-Cookie"] = cookie1
...
ngx.header["Set-Cookie"] = cookie2
```
This simply overwrites cookie1 which IS expected.

The case in my patch is:
```
if a = b then
    local cookies = {cookie1, cookie2, cookie3}
   ngx.header["Set-Cookie"] = cookies
   ngx.exit
end

ngx.header["Set-Cookie"] = cookie99
ngx.exit
```

It is NOT expected that cookie99 gets set as ngx,exit is called before inside the if block and cookie99 is not needed in case the if condition is fired.

Have you tried my patch in real live?

**Comment by C0nw0nk** [comment]
I have allot of junk code to remove your code should run fine and I will have Thursday this week to check it more thoroughly.

You also did this.

```
ngx.say("OK")
ngx.exit(ngx.HTTP_OK)
```

Change it to this. Remove the say it is not needed.

```
ngx.exit(ngx.HTTP_NO_CONTENT)
```

The reason is that response code will send the nginx headers only what is all the requests needs. And the byte size of the content will be 0 bytes what is good on server bandwidth. But your method if you get thousands of requests hitting you the response to serve them all can start climbing into the megabytes and more because the content size is not 0 bytes it is a waste of bandwidth and as we know bandwidth is exspensive. It is a small optimization but when you get millions of requests it really does add up for your bandwidth bill when you do the math of 1 byte x 20million hits. (20mb) but the bigger the content size your server sends the more bandwidth you use across more requests.

**Comment by disaster123** [comment]
thx force pushed new branch

**Pull request merged**
